import { Currency } from '../types';
import { WorkMode } from '../models/offer.models';
import { JobCategory } from '../models/category.models';

export const CANDIDATE_SERVICE_DOMAIN = 'CANDIDATE-SERVICE/api/v1/candidates';
export const OFFER_SERVICE_DOMAIN = 'JOB-OFFER-SERVICE/api/v1/job-offers';
export const COMPANY_SERVICE_DOMAIN = 'COMPANY-SERVICE/api/v1/companies';
export const INTERVIEW_SERVICE_DOMAIN = 'INTERVIEW-SERVICE/api/v1/interviews';
export const APPLICATION_SERVICE_DOMAIN =
  'APPLICATION-SERVICE/api/v1/job-offer-applications';
export const ATTACHMENT_SERVICE_DOMAIN =
  'ATTACHMENT-SERVICE/api/v1/attachments';
export const STATS_SERVICE_DOMAIN = 'STATISTICS-SERVICE/api/v1/statistics';
export const RECENT_OFFERS_VIEWS_DOMAIN =
  'STATISTICS-SERVICE/api/v1/recent-offers';
export const USER_SERVICE_DOMAIN = 'IDENTITY-SERVICE/api/v1/users';
export const AUTH_SERVICE_DOMAIN = 'IDENTITY-SERVICE/api/v1/auth';
export const ATS_SERVICE_DOMAIN = 'ATS-SERVICE/api/v1/ats';

export const DEFAULT_JOB_OFFER_PAGE = 0;
export const DEFAULT_JOB_OFFER_SIZE = 25;
export const DEFAULT_COMPANY_PAGE = 0;
export const DEFAULT_COMPANY_SIZE = 25;
export const DEFAULT_CANDIDATE_PAGE = 0;
export const DEFAULT_CANDIDATE_SIZE = 10;
export const DEFAULT_INTERVIEW_PAGE = 0;
export const DEFAULT_INTERVIEW_SIZE = 25;
export const DEFAULT_APPLICATION_PAGE = 0;
export const DEFAULT_APPLICATION_SIZE = 25;
export const DEFAULT_PROFILE_PAGE = 0;
export const DEFAULT_PROFILE_SIZE = 25;
export const DEFAULT_CANDIDATE_AI_PROCESSING_HISTORY_PAGE = 0;
export const DEFAULT_CANDIDATE_AI_PROCESSING_HISTORY_SIZE = 10;

export const APP_ROLES = {
  HR_ADMIN: 'HR_ADMIN',
  HR: 'HR',
  RECRUITER: 'RECRUITER',
  VALIDATOR: 'VALIDATOR',
};

export const CATEGORIES = [
  { name: 'Technology', value: 'Technology' },
  { name: 'Healthcare', value: 'Healthcare' },
  { name: 'Education', value: 'Education' },
  { name: 'Finance', value: 'Finance' },
  { name: 'Other', value: 'Other' },
];

export const OFFER_STATUS_OPTIONS = [
  { name: 'OPEN', value: 'OPEN' },
  { name: 'HOLD', value: 'HOLD' },
  { name: 'CLOSE', value: 'CLOSE' },
];

export const SKILL_TYPES = [
  { name: 'TECHNICAL_SKILL', value: 'TECHNICAL_SKILL' },
  { name: 'FUNCTIONAL_SKILL', value: 'FUNCTIONAL_SKILL' },
];

export const EMPLOYMENT_TYPES = [
  { name: 'FULLTIME', value: 'FULL_TIME' },
  { name: 'PART_TIME', value: 'PART_TIME' },
];

export const WORK_MODES: { name: string; value: WorkMode }[] = [
  { name: 'ONSITE', value: 'ONSITE' },
  { name: 'REMOTE', value: 'REMOTE' },
  { name: 'HYBRID', value: 'HYBRID' },
];

export const PROFICIENCY_OPTIONS = [
  { name: 'EXPERT', value: 'EXPERT' },
  { name: 'ADVANCED', value: 'ADVANCED' },
  { name: 'INTERMEDIATE', value: 'INTERMEDIATE' },
  { name: 'BEGINNER', value: 'BEGINNER' },
];

export const REQUIREMENT_LEVEL_OPTIONS = [
  { name: 'REQUIRED', value: 'REQUIRED' },
  { name: 'OPTIONAL', value: 'OPTIONAL' },
  { name: 'PREFERRED', value: 'PREFERRED' },
];

export const LANGUAGE_PROFICIENCY_OPTIONS = [
  { name: 'NATIVE', value: 'NATIVE' },
  { name: 'ADVANCED', value: 'ADVANCED' },
  { name: 'INTERMEDIATE', value: 'INTERMEDIATE' },
  { name: 'BEGINNER', value: 'BEGINNER' },
];

export const JOB_CATEGORIES = Object.values(JobCategory).map((category) => ({
  name: category,
  value: category,
}));

export const CURRENCIES: Currency[] = [
  { name: 'Moroccan Dirham', code: 'MAD', symbol: 'DH', locale: 'en-MA' },
  { name: 'US Dollar', code: 'USD', symbol: '$', locale: 'en-US' },
  { name: 'Euro', code: 'EUR', symbol: '€', locale: 'de-DE' },
  { name: 'British Pound', code: 'GBP', symbol: '£', locale: 'en-GB' },
  { name: 'Swiss Franc', code: 'CHF', symbol: 'Fr.', locale: 'de-CH' },
  { name: 'Swedish Krona', code: 'SEK', symbol: 'kr', locale: 'sv-SE' },
  { name: 'Norwegian Krone', code: 'NOK', symbol: 'kr', locale: 'nb-NO' },
  { name: 'Danish Krone', code: 'DKK', symbol: 'kr', locale: 'da-DK' },
  { name: 'Polish Złoty', code: 'PLN', symbol: 'zł', locale: 'pl-PL' },
  { name: 'Czech Koruna', code: 'CZK', symbol: 'Kč', locale: 'cs-CZ' },
  { name: 'Hungarian Forint', code: 'HUF', symbol: 'Ft', locale: 'hu-HU' },
  { name: 'Romanian Leu', code: 'RON', symbol: 'lei', locale: 'ro-RO' },
  { name: 'Bulgarian Lev', code: 'BGN', symbol: 'лв', locale: 'bg-BG' },
  { name: 'Croatian Kuna', code: 'HRK', symbol: 'kn', locale: 'hr-HR' },
  { name: 'Serbian Dinar', code: 'RSD', symbol: 'дин.', locale: 'sr-RS' },
  { name: 'Ukrainian Hryvnia', code: 'UAH', symbol: '₴', locale: 'uk-UA' },
  { name: 'US Dollar', code: 'USD', symbol: '$', locale: 'en-US' },
  { name: 'Japanese Yen', code: 'JPY', symbol: '¥', locale: 'ja-JP' },
  { name: 'Canadian Dollar', code: 'CAD', symbol: 'C$', locale: 'en-CA' },
  { name: 'Australian Dollar', code: 'AUD', symbol: 'A$', locale: 'en-AU' },
];
export const CURRENCIES_FR: Currency[] = [
  { name: 'Dirham marocain', code: 'MAD', symbol: 'DH', locale: 'fr-MA' },
  { name: 'Dollar américain', code: 'USD', symbol: '$', locale: 'fr-US' },
  { name: 'Euro', code: 'EUR', symbol: '€', locale: 'fr-FR' },
  { name: 'Livre sterling', code: 'GBP', symbol: '£', locale: 'fr-GB' },
  { name: 'Franc suisse', code: 'CHF', symbol: 'Fr.', locale: 'fr-CH' },
  { name: 'Couronne suédoise', code: 'SEK', symbol: 'kr', locale: 'fr-SE' },
  { name: 'Couronne norvégienne', code: 'NOK', symbol: 'kr', locale: 'fr-NO' },
  { name: 'Couronne danoise', code: 'DKK', symbol: 'kr', locale: 'fr-DK' },
  { name: 'Złoty polonais', code: 'PLN', symbol: 'zł', locale: 'fr-PL' },
  { name: 'Couronne tchèque', code: 'CZK', symbol: 'Kč', locale: 'fr-CZ' },
  { name: 'Forint hongrois', code: 'HUF', symbol: 'Ft', locale: 'fr-HU' },
  { name: 'Leu roumain', code: 'RON', symbol: 'lei', locale: 'fr-RO' },
  { name: 'Lev bulgare', code: 'BGN', symbol: 'лв', locale: 'fr-BG' },
  { name: 'Kuna croate', code: 'HRK', symbol: 'kn', locale: 'fr-HR' },
  { name: 'Dinar serbe', code: 'RSD', symbol: 'дин.', locale: 'fr-RS' },
  { name: 'Hryvnia ukrainienne', code: 'UAH', symbol: '₴', locale: 'fr-UA' },
  { name: 'Yen japonais', code: 'JPY', symbol: '¥', locale: 'fr-JP' },
  { name: 'Dollar canadien', code: 'CAD', symbol: 'C$', locale: 'fr-CA' },
  { name: 'Dollar australien', code: 'AUD', symbol: 'A$', locale: 'fr-AU' },
];

// French version
export const LANGUAGE_OPTIONS_FR = [
  { name: 'Abkhaze', value: 'ABKHAZIAN' },
  { name: 'Aceh', value: 'ACEH' },
  { name: 'Acoli', value: 'ACHOLI' },
  { name: 'Afar', value: 'AFAR' },
  { name: 'Afrikaans', value: 'AFRIKAANS' },
  { name: 'Akan', value: 'AKAN' },
  { name: 'Albanais', value: 'ALBANIAN' },
  { name: 'Allemand', value: 'GERMAN' },
  { name: 'Alur', value: 'ALUR' },
  { name: 'Amharique', value: 'AMHARIC' },
  { name: 'Anglais', value: 'ENGLISH' },
  { name: 'Arabe', value: 'ARABIC' },
  { name: 'Arménien', value: 'ARMENIAN' },
  { name: 'Assamais', value: 'ASSAMESE' },
  { name: 'Avar', value: 'AVAR' },
  { name: 'Awadhi', value: 'AWADHI' },
  { name: 'Aymara', value: 'AYMARA' },
  { name: 'Azerbaïdjanais', value: 'AZERBAIJANI' },
  { name: 'Bachkir', value: 'BASHKIR' },
  { name: 'Balinais', value: 'BALINESE' },
  { name: 'Baloutchi', value: 'BALOCHI' },
  { name: 'Bambara', value: 'BAMBARA' },
  { name: 'Baoulé', value: 'BAOULE' },
  { name: 'Basque', value: 'BASQUE' },
  { name: 'Batak Karo', value: 'BATAK_KARO' },
  { name: 'Batak simalungun', value: 'BATAK_SIMALUNGUN' },
  { name: 'Batak toba', value: 'BATAK_TOBA' },
  { name: 'Bemba', value: 'BEMBA' },
  { name: 'Bengali', value: 'BENGALI' },
  { name: 'Betawi', value: 'BETAVI' },
  { name: 'Bhodjpouri', value: 'BHOJPURI' },
  { name: 'Biélorusse', value: 'BELARUSIAN' },
  { name: 'Bikol', value: 'BIKOL' },
  { name: 'Birman', value: 'BURMESE' },
  { name: 'Bosniaque', value: 'BOSNIAN' },
  { name: 'Bouriate', value: 'BURYAT' },
  { name: 'Breton', value: 'BRETON' },
  { name: 'Bulgare', value: 'BULGARIAN' },
  { name: 'Cantonais', value: 'CANTONESE' },
  { name: 'Catalan', value: 'CATALAN' },
  { name: 'Cebuano', value: 'CEBUANO' },
  { name: 'Chamorro', value: 'CHAMORRO' },
  { name: 'Chewa', value: 'CHEWA' },
  { name: 'Chinois (simplifié)', value: 'CHINESE_SIMPLIFIED' },
  { name: 'Chinois (traditionnel)', value: 'CHINESE_TRADITIONAL' },
  { name: 'Chuuk', value: 'CHUUKESE' },
  { name: 'Cingalais', value: 'SINHALA' },
  { name: 'Coréen', value: 'KOREAN' },
  { name: 'Corse', value: 'CORSICAN' },
  { name: 'Créole haïtien', value: 'HAITIAN_CREOLE' },
  { name: 'Créole mauricien', value: 'MAURITIAN_CREOLE' },
  { name: 'Créole seychellois', value: 'SEYCHELLOIS_CREOLE' },
  { name: 'Croate', value: 'CROATIAN' },
  { name: 'Danois', value: 'DANISH' },
  { name: 'Dari', value: 'DARI' },
  { name: 'Dinka', value: 'DINKA' },
  { name: 'Dioula', value: 'DYULA' },
  { name: 'Dogri', value: 'DOGRI' },
  { name: 'Dombe', value: 'DOMBE' },
  { name: 'Dzongkha', value: 'DZONGKHA' },
  { name: 'Espagnol', value: 'SPANISH' },
  { name: 'Espéranto', value: 'ESPERANTO' },
  { name: 'Estonien', value: 'ESTONIAN' },
  { name: 'Éwé', value: 'EWE' },
  { name: 'Féroïen', value: 'FAROESE' },
  { name: 'Fidjien', value: 'FIJIAN' },
  { name: 'Finnois', value: 'FINNISH' },
  { name: 'Fon', value: 'FON' },
  { name: 'Français', value: 'FRENCH' },
  { name: 'Frioulan', value: 'FRIULIAN' },
  { name: 'Frison occidental', value: 'WESTERN_FRISIAN' },
  { name: 'Ga', value: 'GA' },
  { name: 'Gaélique écossais', value: 'SCOTTISH_GAELIC' },
  { name: 'Galicien', value: 'GALICIAN' },
  { name: 'Gallois', value: 'WELSH' },
  { name: 'Ganda', value: 'GANDA' },
  { name: 'Géorgien', value: 'GEORGIAN' },
  { name: 'Goudjarati', value: 'GUJARATI' },
  { name: 'Grec', value: 'GREEK' },
  { name: 'Groenlandais', value: 'GREENLANDIC' },
  { name: 'Guarani', value: 'GUARANI' },
  { name: 'Hakha Chin', value: 'HAKHA_CHIN' },
  { name: 'Haoussa', value: 'HAUSA' },
  { name: 'Hawaïen', value: 'HAWAIIAN' },
  { name: 'Hébreu', value: 'HEBREW' },
  { name: 'Hiligaynon', value: 'HILIGAYNON' },
  { name: 'Hindi', value: 'HINDI' },
  { name: 'Hmong', value: 'HMONG' },
  { name: 'Hongrois', value: 'HUNGARIAN' },
  { name: 'Hunsrik', value: 'HUNSRICK' },
  { name: 'Iakoute', value: 'YAKUT' },
  { name: 'Iban', value: 'IBAN' },
  { name: 'Igbo', value: 'IGBO' },
  { name: 'Ilocano', value: 'ILOCANO' },
  { name: 'Indonésien', value: 'INDONESIAN' },
  { name: 'Irlandais', value: 'IRISH' },
  { name: 'Islandais', value: 'ICELANDIC' },
  { name: 'Italien', value: 'ITALIAN' },
  { name: 'Japonais', value: 'JAPANESE' },
  { name: 'Javanais', value: 'JAVANESE' },
  { name: 'Jingpo', value: 'JINGPO' },
  { name: 'Kannada', value: 'KANNADA' },
  { name: 'Kanouri', value: 'KANURI' },
  { name: 'Kazakh', value: 'KAZAKH' },
  { name: 'Khasi', value: 'KHASI' },
  { name: 'Khmer', value: 'KHMER' },
  { name: 'Kiga', value: 'KIGA' },
  { name: 'Kikongo', value: 'KIKONGO' },
  { name: 'Kinyarwanda', value: 'KINYARWANDA' },
  { name: 'Kirghize', value: 'KYRGYZ' },
  { name: 'Kituba', value: 'KITUBA' },
  { name: 'Kok Borok', value: 'KOK_BOROK' },
  { name: 'Komi', value: 'KOMI' },
  { name: 'Konkani', value: 'KONKANI' },
  { name: 'Krio', value: 'KRIO' },
  { name: 'Kurde', value: 'KURDISH' },
  { name: 'Lao', value: 'LAO' },
  { name: 'Latgalien', value: 'LATGALIAN' },
  { name: 'Latin', value: 'LATIN' },
  { name: 'Letton', value: 'LATVIAN' },
  { name: 'Ligure', value: 'LIGURIAN' },
  { name: 'Limbourgeois', value: 'LIMBURGISH' },
  { name: 'Lingala', value: 'LINGALA' },
  { name: 'Lituanien', value: 'LITHUANIAN' },
  { name: 'Lombard', value: 'LOMBARD' },
  { name: 'Luo', value: 'LUO' },
  { name: 'Lushaï', value: 'LUSHAI' },
  { name: 'Luxembourgeois', value: 'LUXEMBOURGISH' },
  { name: 'Macédonien', value: 'MACEDONIAN' },
  { name: 'Madurais', value: 'MADURESE' },
  { name: 'Maïthili', value: 'MAITHILI' },
  { name: 'Makassar', value: 'MAKASSAR' },
  { name: 'Malais', value: 'MALAY' },
  { name: 'Malais (arabe)', value: 'MALAY_ARABIC' },
  { name: 'Malayalam', value: 'MALAYALAM' },
  { name: 'Maldivien', value: 'DHIVEHI' },
  { name: 'Malgache', value: 'MALAGASY' },
  { name: 'Maltais', value: 'MALTESE' },
  { name: 'Mam', value: 'MAM' },
  { name: 'Manipuri', value: 'MANIPURI' },
  { name: 'Mannois', value: 'MANX' },
  { name: 'Maori', value: 'MAORI' },
  { name: 'Marathi', value: 'MARATHI' },
  { name: 'Mari des prairies', value: 'MEADOW_MARI' },
  { name: 'Marshallais', value: 'MARSHALLESE' },
  { name: 'Marwarî', value: 'MARWARI' },
  { name: 'Maya yucatèque', value: 'YUCATEC_MAYA' },
  { name: 'Minangkabau', value: 'MINANGKABAU' },
  { name: 'Mongol', value: 'MONGOLIAN' },
  { name: "N'ko", value: 'NKO' },
  { name: 'Nahuatl', value: 'NAHUATL' },
  { name: 'Ndau', value: 'NDAU' },
  { name: 'Ndébélé du Sud', value: 'SOUTH_NDEBELE' },
  { name: 'Néerlandais', value: 'DUTCH' },
  { name: 'Népalais', value: 'NEPALI' },
  { name: 'Newari', value: 'NEWARI' },
  { name: 'Norvégien', value: 'NORWEGIAN' },
  { name: 'Nuer', value: 'NUER' },
  { name: 'Occitan', value: 'OCCITAN' },
  { name: 'Odia', value: 'ODIA' },
  { name: 'Oromo', value: 'OROMO' },
  { name: 'Ossète', value: 'OSSETIC' },
  { name: 'Oudmourte', value: 'UDMURT' },
  { name: 'Ouïghour', value: 'UYGHUR' },
  { name: 'Ourdou', value: 'URDU' },
  { name: 'Ouzbek', value: 'UZBEK' },
  { name: 'Pachto', value: 'PASHTO' },
  { name: 'Pampangan', value: 'PAMPANGAN' },
  { name: 'Pangasinan', value: 'PANGASINAN' },
  { name: 'Papiamento', value: 'PAPIAMENTO' },
  { name: 'Patois jamaïcain', value: 'JAMAICAN_PATOIS' },
  { name: 'Pendjabi', value: 'PUNJABI' },
  { name: 'Pendjabi (arabe)', value: 'PUNJABI_ARABIC' },
  { name: 'Persan', value: 'PERSIAN' },
  { name: 'Peul', value: 'FULA' },
  { name: 'Polonais', value: 'POLISH' },
  { name: 'Portugais', value: 'PORTUGUESE' },
  { name: 'Portugais (Portugal)', value: 'PORTUGUESE_PORTUGAL' },
  { name: "Q'eqchi'", value: 'QEQCHI' },
  { name: 'Quechua', value: 'QUECHUA' },
  { name: 'Romani', value: 'ROMANI' },
  { name: 'Roumain', value: 'ROMANIAN' },
  { name: 'Roundi', value: 'RUNDI' },
  { name: 'Russe', value: 'RUSSIAN' },
  { name: 'Same du Nord', value: 'NORTHERN_SAMI' },
  { name: 'Samoan', value: 'SAMOAN' },
  { name: 'Sango', value: 'SANGO' },
  { name: 'Sanskrit', value: 'SANSKRIT' },
  { name: 'Santali', value: 'SANTALI' },
  { name: 'Serbe', value: 'SERBIAN' },
  { name: 'Shan', value: 'SHAN' },
  { name: 'Shona', value: 'SHONA' },
  { name: 'Sicilien', value: 'SICILIAN' },
  { name: 'Silésien', value: 'SILESIAN' },
  { name: 'Sindhi', value: 'SINDHI' },
  { name: 'Slovaque', value: 'SLOVAK' },
  { name: 'Slovène', value: 'SLOVENE' },
  { name: 'Somali', value: 'SOMALI' },
  { name: 'Sorani', value: 'SORANI' },
  { name: 'Sotho du Nord', value: 'NORTHERN_SOTHO' },
  { name: 'Sotho du Sud', value: 'SOUTHERN_SOTHO' },
  { name: 'Soundanais', value: 'SUNDANESE' },
  { name: 'Soussou', value: 'SUSU' },
  { name: 'Suédois', value: 'SWEDISH' },
  { name: 'Swahili', value: 'SWAHILI' },
  { name: 'Swati', value: 'SWATI' },
  { name: 'Tadjik', value: 'TAJIK' },
  { name: 'Tagalog', value: 'TAGALOG' },
  { name: 'Tahitien', value: 'TAHITIAN' },
  { name: 'Tamazight', value: 'TAMAZIGHT' },
  { name: 'Tamazight (Tifinagh)', value: 'TAMAZIGHT_TIFINAGH' },
  { name: 'Tamoul', value: 'TAMIL' },
  { name: 'Tatar', value: 'TATAR' },
  { name: 'Tatar de Crimée', value: 'CRIMEAN_TATAR' },
  { name: 'Tchèque', value: 'CZECH' },
  { name: 'Tchétchène', value: 'CHECHEN' },
  { name: 'Tchouvache', value: 'CHUVASH' },
  { name: 'Télougou', value: 'TELUGU' },
  { name: 'Tétoum', value: 'TETUM' },
  { name: 'Thaï', value: 'THAI' },
  { name: 'Tibétain', value: 'TIBETAN' },
  { name: 'Tigrigna', value: 'TIGRINYA' },
  { name: 'Tiv', value: 'TIV' },
  { name: 'Tok pisin', value: 'TOK_PISIN' },
  { name: 'Tongien', value: 'TONGAN' },
  { name: 'Toulou', value: 'TULU' },
  { name: 'Touvain', value: 'TUVAN' },
  { name: 'Tsonga', value: 'TSONGA' },
  { name: 'Tswana', value: 'TSWANA' },
  { name: 'Tumbuka', value: 'TUMBUKA' },
  { name: 'Turc', value: 'TURKISH' },
  { name: 'Turkmène', value: 'TURKMEN' },
  { name: 'Ukrainien', value: 'UKRAINIAN' },
  { name: 'Venda', value: 'VENDA' },
  { name: 'Vénitien', value: 'VENETIAN' },
  { name: 'Vietnamien', value: 'VIETNAMESE' },
  { name: 'Waray', value: 'WARAY' },
  { name: 'Wolof', value: 'WOLOF' },
  { name: 'Xhosa', value: 'XHOSA' },
  { name: 'Yiddish', value: 'YIDDISH' },
  { name: 'Yoruba', value: 'YORUBA' },
  { name: 'Zapotèque', value: 'ZAPOTEC' },
  { name: 'Zoulou', value: 'ZULU' },
];

// English version
export const LANGUAGE_OPTIONS_EN = [
  { name: 'Abkhazian', value: 'ABKHAZIAN' },
  { name: 'Aceh', value: 'ACEH' },
  { name: 'Acholi', value: 'ACHOLI' },
  { name: 'Afar', value: 'AFAR' },
  { name: 'Afrikaans', value: 'AFRIKAANS' },
  { name: 'Akan', value: 'AKAN' },
  { name: 'Albanian', value: 'ALBANIAN' },
  { name: 'German', value: 'GERMAN' },
  { name: 'Alur', value: 'ALUR' },
  { name: 'Amharic', value: 'AMHARIC' },
  { name: 'English', value: 'ENGLISH' },
  { name: 'Arabic', value: 'ARABIC' },
  { name: 'Armenian', value: 'ARMENIAN' },
  { name: 'Assamese', value: 'ASSAMESE' },
  { name: 'Avar', value: 'AVAR' },
  { name: 'Awadhi', value: 'AWADHI' },
  { name: 'Aymara', value: 'AYMARA' },
  { name: 'Azerbaijani', value: 'AZERBAIJANI' },
  { name: 'Bashkir', value: 'BASHKIR' },
  { name: 'Balinese', value: 'BALINESE' },
  { name: 'Balochi', value: 'BALOCHI' },
  { name: 'Bambara', value: 'BAMBARA' },
  { name: 'Baoule', value: 'BAOULE' },
  { name: 'Basque', value: 'BASQUE' },
  { name: 'Batak Karo', value: 'BATAK_KARO' },
  { name: 'Batak Simalungun', value: 'BATAK_SIMALUNGUN' },
  { name: 'Batak Toba', value: 'BATAK_TOBA' },
  { name: 'Bemba', value: 'BEMBA' },
  { name: 'Bengali', value: 'BENGALI' },
  { name: 'Betawi', value: 'BETAVI' },
  { name: 'Bhojpuri', value: 'BHOJPURI' },
  { name: 'Belarusian', value: 'BELARUSIAN' },
  { name: 'Bikol', value: 'BIKOL' },
  { name: 'Burmese', value: 'BURMESE' },
  { name: 'Bosnian', value: 'BOSNIAN' },
  { name: 'Buryat', value: 'BURYAT' },
  { name: 'Breton', value: 'BRETON' },
  { name: 'Bulgarian', value: 'BULGARIAN' },
  { name: 'Cantonese', value: 'CANTONESE' },
  { name: 'Catalan', value: 'CATALAN' },
  { name: 'Cebuano', value: 'CEBUANO' },
  { name: 'Chamorro', value: 'CHAMORRO' },
  { name: 'Chewa', value: 'CHEWA' },
  { name: 'Chinese (Simplified)', value: 'CHINESE_SIMPLIFIED' },
  { name: 'Chinese (Traditional)', value: 'CHINESE_TRADITIONAL' },
  { name: 'Chuukese', value: 'CHUUKESE' },
  { name: 'Sinhala', value: 'SINHALA' },
  { name: 'Korean', value: 'KOREAN' },
  { name: 'Corsican', value: 'CORSICAN' },
  { name: 'Haitian Creole', value: 'HAITIAN_CREOLE' },
  { name: 'Mauritian Creole', value: 'MAURITIAN_CREOLE' },
  { name: 'Seychellois Creole', value: 'SEYCHELLOIS_CREOLE' },
  { name: 'Croatian', value: 'CROATIAN' },
  { name: 'Danish', value: 'DANISH' },
  { name: 'Dari', value: 'DARI' },
  { name: 'Dinka', value: 'DINKA' },
  { name: 'Dyula', value: 'DYULA' },
  { name: 'Dogri', value: 'DOGRI' },
  { name: 'Dombe', value: 'DOMBE' },
  { name: 'Dzongkha', value: 'DZONGKHA' },
  { name: 'Spanish', value: 'SPANISH' },
  { name: 'Esperanto', value: 'ESPERANTO' },
  { name: 'Estonian', value: 'ESTONIAN' },
  { name: 'Ewe', value: 'EWE' },
  { name: 'Faroese', value: 'FAROESE' },
  { name: 'Fijian', value: 'FIJIAN' },
  { name: 'Finnish', value: 'FINNISH' },
  { name: 'Fon', value: 'FON' },
  { name: 'French', value: 'FRENCH' },
  { name: 'Friulian', value: 'FRIULIAN' },
  { name: 'Western Frisian', value: 'WESTERN_FRISIAN' },
  { name: 'Ga', value: 'GA' },
  { name: 'Scottish Gaelic', value: 'SCOTTISH_GAELIC' },
  { name: 'Galician', value: 'GALICIAN' },
  { name: 'Welsh', value: 'WELSH' },
  { name: 'Ganda', value: 'GANDA' },
  { name: 'Georgian', value: 'GEORGIAN' },
  { name: 'Gujarati', value: 'GUJARATI' },
  { name: 'Greek', value: 'GREEK' },
  { name: 'Greenlandic', value: 'GREENLANDIC' },
  { name: 'Guarani', value: 'GUARANI' },
  { name: 'Hakha Chin', value: 'HAKHA_CHIN' },
  { name: 'Hausa', value: 'HAUSA' },
  { name: 'Hawaiian', value: 'HAWAIIAN' },
  { name: 'Hebrew', value: 'HEBREW' },
  { name: 'Hiligaynon', value: 'HILIGAYNON' },
  { name: 'Hindi', value: 'HINDI' },
  { name: 'Hmong', value: 'HMONG' },
  { name: 'Hungarian', value: 'HUNGARIAN' },
  { name: 'Hunsrik', value: 'HUNSRICK' },
  { name: 'Yakut', value: 'YAKUT' },
  { name: 'Iban', value: 'IBAN' },
  { name: 'Igbo', value: 'IGBO' },
  { name: 'Ilocano', value: 'ILOCANO' },
  { name: 'Indonesian', value: 'INDONESIAN' },
  { name: 'Irish', value: 'IRISH' },
  { name: 'Icelandic', value: 'ICELANDIC' },
  { name: 'Italian', value: 'ITALIAN' },
  { name: 'Japanese', value: 'JAPANESE' },
  { name: 'Javanese', value: 'JAVANESE' },
  { name: 'Jingpo', value: 'JINGPO' },
  { name: 'Kannada', value: 'KANNADA' },
  { name: 'Kanuri', value: 'KANURI' },
  { name: 'Kazakh', value: 'KAZAKH' },
  { name: 'Khasi', value: 'KHASI' },
  { name: 'Khmer', value: 'KHMER' },
  { name: 'Kiga', value: 'KIGA' },
  { name: 'Kikongo', value: 'KIKONGO' },
  { name: 'Kinyarwanda', value: 'KINYARWANDA' },
  { name: 'Kyrgyz', value: 'KYRGYZ' },
  { name: 'Kituba', value: 'KITUBA' },
  { name: 'Kok Borok', value: 'KOK_BOROK' },
  { name: 'Komi', value: 'KOMI' },
  { name: 'Konkani', value: 'KONKANI' },
  { name: 'Krio', value: 'KRIO' },
  { name: 'Kurdish', value: 'KURDISH' },
  { name: 'Lao', value: 'LAO' },
  { name: 'Latgalian', value: 'LATGALIAN' },
  { name: 'Latin', value: 'LATIN' },
  { name: 'Latvian', value: 'LATVIAN' },
  { name: 'Ligurian', value: 'LIGURIAN' },
  { name: 'Limburgish', value: 'LIMBURGISH' },
  { name: 'Lingala', value: 'LINGALA' },
  { name: 'Lithuanian', value: 'LITHUANIAN' },
  { name: 'Lombard', value: 'LOMBARD' },
  { name: 'Luo', value: 'LUO' },
  { name: 'Lushai', value: 'LUSHAI' },
  { name: 'Luxembourgish', value: 'LUXEMBOURGISH' },
  { name: 'Macedonian', value: 'MACEDONIAN' },
  { name: 'Madurese', value: 'MADURESE' },
  { name: 'Maithili', value: 'MAITHILI' },
  { name: 'Makassar', value: 'MAKASSAR' },
  { name: 'Malay', value: 'MALAY' },
  { name: 'Malay (Arabic)', value: 'MALAY_ARABIC' },
  { name: 'Malayalam', value: 'MALAYALAM' },
  { name: 'Dhivehi', value: 'DHIVEHI' },
  { name: 'Malagasy', value: 'MALAGASY' },
  { name: 'Maltese', value: 'MALTESE' },
  { name: 'Mam', value: 'MAM' },
  { name: 'Manipuri', value: 'MANIPURI' },
  { name: 'Manx', value: 'MANX' },
  { name: 'Maori', value: 'MAORI' },
  { name: 'Marathi', value: 'MARATHI' },
  { name: 'Meadow Mari', value: 'MEADOW_MARI' },
  { name: 'Marshallese', value: 'MARSHALLESE' },
  { name: 'Marwari', value: 'MARWARI' },
  { name: 'Yucatec Maya', value: 'YUCATEC_MAYA' },
  { name: 'Minangkabau', value: 'MINANGKABAU' },
  { name: 'Mongolian', value: 'MONGOLIAN' },
  { name: "N'Ko", value: 'NKO' },
  { name: 'Nahuatl', value: 'NAHUATL' },
  { name: 'Ndau', value: 'NDAU' },
  { name: 'South Ndebele', value: 'SOUTH_NDEBELE' },
  { name: 'Dutch', value: 'DUTCH' },
  { name: 'Nepali', value: 'NEPALI' },
  { name: 'Newari', value: 'NEWARI' },
  { name: 'Norwegian', value: 'NORWEGIAN' },
  { name: 'Nuer', value: 'NUER' },
  { name: 'Occitan', value: 'OCCITAN' },
  { name: 'Odia', value: 'ODIA' },
  { name: 'Oromo', value: 'OROMO' },
  { name: 'Ossetic', value: 'OSSETIC' },
  { name: 'Udmurt', value: 'UDMURT' },
  { name: 'Uyghur', value: 'UYGHUR' },
  { name: 'Urdu', value: 'URDU' },
  { name: 'Uzbek', value: 'UZBEK' },
  { name: 'Pashto', value: 'PASHTO' },
  { name: 'Pampangan', value: 'PAMPANGAN' },
  { name: 'Pangasinan', value: 'PANGASINAN' },
  { name: 'Papiamento', value: 'PAPIAMENTO' },
  { name: 'Jamaican Patois', value: 'JAMAICAN_PATOIS' },
  { name: 'Punjabi', value: 'PUNJABI' },
  { name: 'Punjabi (Arabic)', value: 'PUNJABI_ARABIC' },
  { name: 'Persian', value: 'PERSIAN' },
  { name: 'Fula', value: 'FULA' },
  { name: 'Polish', value: 'POLISH' },
  { name: 'Portuguese', value: 'PORTUGUESE' },
  { name: 'Portuguese (Portugal)', value: 'PORTUGUESE_PORTUGAL' },
  { name: "Q'eqchi'", value: 'QEQCHI' },
  { name: 'Quechua', value: 'QUECHUA' },
  { name: 'Romani', value: 'ROMANI' },
  { name: 'Romanian', value: 'ROMANIAN' },
  { name: 'Rundi', value: 'RUNDI' },
  { name: 'Russian', value: 'RUSSIAN' },
  { name: 'Northern Sami', value: 'NORTHERN_SAMI' },
  { name: 'Samoan', value: 'SAMOAN' },
  { name: 'Sango', value: 'SANGO' },
  { name: 'Sanskrit', value: 'SANSKRIT' },
  { name: 'Santali', value: 'SANTALI' },
  { name: 'Serbian', value: 'SERBIAN' },
  { name: 'Shan', value: 'SHAN' },
  { name: 'Shona', value: 'SHONA' },
  { name: 'Sicilian', value: 'SICILIAN' },
  { name: 'Silesian', value: 'SILESIAN' },
  { name: 'Sindhi', value: 'SINDHI' },
  { name: 'Slovak', value: 'SLOVAK' },
  { name: 'Slovene', value: 'SLOVENE' },
  { name: 'Somali', value: 'SOMALI' },
  { name: 'Sorani', value: 'SORANI' },
  { name: 'Northern Sotho', value: 'NORTHERN_SOTHO' },
  { name: 'Southern Sotho', value: 'SOUTHERN_SOTHO' },
  { name: 'Sundanese', value: 'SUNDANESE' },
  { name: 'Susu', value: 'SUSU' },
  { name: 'Swedish', value: 'SWEDISH' },
  { name: 'Swahili', value: 'SWAHILI' },
  { name: 'Swati', value: 'SWATI' },
  { name: 'Tajik', value: 'TAJIK' },
  { name: 'Tagalog', value: 'TAGALOG' },
  { name: 'Tahitian', value: 'TAHITIAN' },
  { name: 'Tamazight', value: 'TAMAZIGHT' },
  { name: 'Tamazight (Tifinagh)', value: 'TAMAZIGHT_TIFINAGH' },
  { name: 'Tamil', value: 'TAMIL' },
  { name: 'Tatar', value: 'TATAR' },
  { name: 'Crimean Tatar', value: 'CRIMEAN_TATAR' },
  { name: 'Czech', value: 'CZECH' },
  { name: 'Chechen', value: 'CHECHEN' },
  { name: 'Chuvash', value: 'CHUVASH' },
  { name: 'Telugu', value: 'TELUGU' },
  { name: 'Tetum', value: 'TETUM' },
  { name: 'Thai', value: 'THAI' },
  { name: 'Tibetan', value: 'TIBETAN' },
  { name: 'Tigrinya', value: 'TIGRINYA' },
  { name: 'Tiv', value: 'TIV' },
  { name: 'Tok Pisin', value: 'TOK_PISIN' },
  { name: 'Tongan', value: 'TONGAN' },
  { name: 'Tulu', value: 'TULU' },
  { name: 'Tuvan', value: 'TUVAN' },
  { name: 'Tsonga', value: 'TSONGA' },
  { name: 'Tswana', value: 'TSWANA' },
  { name: 'Tumbuka', value: 'TUMBUKA' },
  { name: 'Turkish', value: 'TURKISH' },
  { name: 'Turkmen', value: 'TURKMEN' },
  { name: 'Ukrainian', value: 'UKRAINIAN' },
  { name: 'Venda', value: 'VENDA' },
  { name: 'Venetian', value: 'VENETIAN' },
  { name: 'Vietnamese', value: 'VIETNAMESE' },
  { name: 'Waray', value: 'WARAY' },
  { name: 'Wolof', value: 'WOLOF' },
  { name: 'Xhosa', value: 'XHOSA' },
  { name: 'Yiddish', value: 'YIDDISH' },
  { name: 'Yoruba', value: 'YORUBA' },
  { name: 'Zapotec', value: 'ZAPOTEC' },
  { name: 'Zulu', value: 'ZULU' },
];

export const CANDIDATE_WORK_SEARCH_OPTIONS = [
  { name: 'ACTIVELY_SEARCHING', value: 'ACTIVE_SEARCH' },
  { name: 'OPEN_TO_OPPORTUNITIES', value: 'OPEN_TO_OPPORTUNITIES' },
];

export const CANDIDATE_PROGRESS_LEVEL_OPTIONS = [
  { name: 'LOW', value: 'LOW' },
  { name: 'ADVANCED', value: 'ADVANCED' },
  { name: 'VERY_ADVANCED', value: 'VERY_ADVANCED' },
];

export const CANDIDATE_AVAILABILITY_STATUS_OPTIONS = [
  { name: 'IMMEDIATELY_AVAILABLE', value: 'IMMEDIATELY_AVAILABLE' },
  { name: 'WITH_NOTICE', value: 'WITH_NOTICE' },
];

export const INTERVIEW_TYPE_OPTIONS = [
  { name: 'TECHNICAL_INTERVIEW', value: 'TECHNICAL' },
  { name: 'HR_INTERVIEW', value: 'HR' },
];

export const INTERVIEW_STATUS_OPTIONS = [
  { name: 'SCHEDULED', value: 'SCHEDULED' },
  { name: 'CANCELLED', value: 'CANCELLED' },
  { name: 'IN_PROGRESS', value: 'IN_PROGRESS' },
  { name: 'COMPLETED', value: 'COMPLETED' },
  { name: 'RESCHEDULED', value: 'RESCHEDULED' },
  { name: 'NO_SHOW', value: 'NO_SHOW' },
];
export const YEARS_OF_EXPERIENCE_OPTIONS = [
  { name: '0-1', value: '0-1' },
  { name: '1-3', value: '1-3' },
  { name: '3-5', value: '3-5' },
  { name: 'MORE_THAN_5', value: 'MORE_THAN_5' },
];

export const COMPANY_SIZE_OPTIONS = [
  { name: '1-10', value: '1-10' },
  { name: '11-50', value: '11-50' },
  { name: '51-200', value: '51-200' },
  { name: '201-500', value: '201-500' },
  { name: '501-1000', value: '501-1000' },
  { name: '1001-5000', value: '1001-5000' },
  { name: '5001-10000', value: '5001-10000' },
  { name: '10000+', value: '10000+' },
];

export const CANDIDATE_CREATION_SOURCE_OPTIONS = [
  { name: 'MANUAL', value: 'MANUAL' },
  { name: 'AI_GENERATED', value: 'AI_GENERATED' },
  { name: 'EXTERNAL_SYNC', value: 'EXTERNAL_SYNC' },
];

export const CANDIDATE_VALIDATION_STATUS_OPTIONS = [
  { name: 'VERIFIED', value: 'VERIFIED' },
  { name: 'INVALIDATED', value: 'INVALIDATED' },
];

export const CANDIDATE_REACHABILITY_STATUS_OPTIONS = [
  { name: 'REACHABLE', value: 'REACHABLE' },
  { name: 'UNREACHABLE', value: 'UNREACHABLE' },
];

export const CONTRACT_TYPE_OPTIONS = [
  { name: 'CDI', value: 'CDI' },
  { name: 'CDD', value: 'CDD' },
  { name: 'INTERNSHIP', value: 'INTERNSHIP' },
  { name: 'FREELANCE_CONTRACT', value: 'FREELANCE_CONTRACT' },
  { name: 'TEMPORARY_CONTRACT', value: 'TEMPORARY_CONTRACT' },
];
